blank_issues_enabled: true
contact_links:
  - name: Meta Support
    url: https://t.me/sadnesstalk 
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://github.com/matalata02
    about: Documentation for getting started with bot.
